Update patch set 3
Patch Set 3:

Hi thanks for the update to 1.1. I logged into Rackspace and tested this morning without success, the image was not found, please check what I've done here:

root@vm1-portal:/opt# cat /opt/config/nexus_docker_repo.txt
nexus3.onap.org:10001
root@vm1-portal:/opt# cat /opt/config/docker_version.txt
1.1-STAGING-latest
root@vm1-portal:/opt# docker pull nexus3.onap.org:10001/onap/cli:1.1-STAGING-latest
Pulling repository nexus3.onap.org:10001/onap/cli
Error: image onap/cli:1.1-STAGING-latest not found

Patch-set: 3