Update patch set 1
Patch Set 1:

> Dileep,
 > 
 > Are the docker images actually available? I can't see them in
 > Nexus. I get the following error when running docker pull:
 > 
 > Pulling repository nexus3.onap.org:10001/onap/optf-osdf
 > Error: image onap/optf-osdf:1.2.0 not found
 > 
 > Marco

Yes. There are some dependent patches in OOF project which needs to be merged first.

Patch-set: 1